apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginx-dst-rule
spec:
  exportTo:
  - "istio-system"
  host: nginx.apps.svc.cluster.local
  subsets:
  - name: mutual
    trafficPolicy:
      tls:
        mode: MUTUAL
        credentialName: client-credential
  - name: passthroughversion
    trafficPolicy:
      tls:
        mode: DISABLE
